name: shelf_api_builder
description: A code generator to create RESTful API endpoints to be integrated with shelf.
version: 1.2.2
homepage: https://github.com/Skycoder42/shelf_api
topics:
  - server
  - shelf
  - dio
  - rest
  - api

environment:
  sdk: ^3.7.0
resolution: workspace

platforms:
  linux:
  macos:
  windows:

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  build_config: ^1.1.2
  code_builder: ^4.10.1
  meta: ^1.16.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_api: ^1.3.2
  source_gen: ^2.0.0
  source_helper: ^1.3.5

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_pre_commit: ^5.4.4
  dart_test_tools: ^6.1.1
  dio: ^5.8.0+1
  source_gen_test: ^1.1.1
  test: ^1.25.15

cider:
  link_template:
    tag: https://github.com/Skycoder42/shelf_api/releases/tag/shelf_api_builder-v%tag%
    diff: https://github.com/Skycoder42/shelf_api/compare/shelf_api_builder-v%from%...shelf_api_builder-v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - analyzer
      - meta
      - path
      - shelf
