name: shelf_api
description: A package to declare rest API endpoints that generate into shelf handlers.
version: 1.3.3
homepage: https://github.com/Skycoder42/shelf_api
topics:
  - server
  - shelf
  - dio
  - rest
  - api

environment:
  sdk: ^3.8.0
resolution: workspace

dependencies:
  dio: ^5.8.0+1
  meta: ^1.16.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  dart_pre_commit: ^5.4.7
  dart_test_tools: ^6.1.1
  mockito: ^5.4.6
  riverpod_generator: ^2.6.5
  stream_channel: ^2.1.4
  test: ^1.25.15

cider:
  link_template:
    tag: https://github.com/Skycoder42/shelf_api/releases/tag/shelf_api-v%tag%
    diff: https://github.com/Skycoder42/shelf_api/compare/shelf_api-v%from%...shelf_api-v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta
      - shelf
