name: shelf_api
description: A package to declare rest API endpoints that generate into shelf handlers.
version: 1.4.1
homepage: https://github.com/Skycoder42/shelf_api
topics:
  - server
  - shelf
  - dio
  - rest
  - api

environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  dio: ^5.9.0
  meta: ^1.17.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  rxdart: ^0.28.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.10.4
  dart_pre_commit: ^6.1.0
  dart_test_tools: ^7.0.1
  mockito: ^5.6.1
  riverpod_generator: ^3.0.3
  stream_channel: ^2.1.4
  test: ^1.26.3

cider:
  link_template:
    tag: https://github.com/Skycoder42/shelf_api/releases/tag/shelf_api-v%tag%
    diff: https://github.com/Skycoder42/shelf_api/compare/shelf_api-v%from%...shelf_api-v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta
      - shelf
